site_name: Гафаров Данил. Отчеты
nav:
  - Home: index.md
  - Lab-1:
    - task 1: lab1/task1.md
    - task 2: lab1/task2.md
    - task 3: lab1/task3.md
    - task 4: lab1/task4.md
    - task 5: lab1/task5.md
theme:
  name: material
